In [6]:
import pandas as pd

In [7]:
gas_df = pd.read_csv('gas.csv', encoding='CP949')
gas_df.head()

   region            gasName                     address           tel
0  서울 서초구  (주)에이치앤디이-서울만남의광장  서울 서초구 양재대로12길 73-71 만남의광장   02-573-7430
1  서울 강남구            강남복지충전소             서울 강남구 밤고개로 200   02-445-3300
2  서울 강동구              암사충전소       서울 강동구 올림픽로 791 GS칼텍스  02-3427-4244
3  서울 강남구            (주)진양가스              서울 강남구 도곡로 142  02-3463-6811
4  서울 강남구          대치에너지주식회사           서울 강남구 남부순환로 3179  02-3412-2828

In [16]:
gu_list = []
addr = gas_df['region']

for i in addr:
    addr = gas_df['region'].str.split( )
    i = i.split( )
    gu_list.append(i[1])
print(gu_list)

['서초구', '강남구', '강동구', '강남구', '강남구', '서초구', '강남구', '서초구', '강동구', '강남구', '강동구', '서초구', '송파구', '송파구', '송파구', '강동구', '송파구', '은평구', '서대문구', '은평구', '은평구', '양천구', '양천구', '구로구', '금천구', '영등포구', '강서구', '구로구', '강서구', '영등포구', '구로구', '강서구', '동작구', '강서구', '강서구', '관악구', '구로구', '양천구', '구로구', '영등포구', '강서구', '양천구', '강서구', '강서구', '관악구', '양천구', '양천구', '강서구', '강서구', '강서구', '강서구', '동대문구', '중랑구', '도봉구', '강북구', '광진구', '노원구', '강북구', '중랑구', '도봉구', '강북구', '성동구', '동대문구', '도봉구', '노원구', '노원구', '중랑구', '중랑구', '노원구', '동대문구', '성동구', '광진구', '성북구', '성북구', '광진구', '노원구', '동대문구', '노원구']

In [9]:
gas_df['gas'] = pd.Series(gu_list)

In [10]:
gas_df

     region            gasName                     address           tel   gas
0    서울 서초구  (주)에이치앤디이-서울만남의광장  서울 서초구 양재대로12길 73-71 만남의광장   02-573-7430   서초구
1    서울 강남구            강남복지충전소             서울 강남구 밤고개로 200   02-445-3300   강남구
2    서울 강동구              암사충전소       서울 강동구 올림픽로 791 GS칼텍스  02-3427-4244   강동구
3    서울 강남구            (주)진양가스              서울 강남구 도곡로 142  02-3463-6811   강남구
4    서울 강남구          대치에너지주식회사           서울 강남구 남부순환로 3179  02-3412-2828   강남구
..      ...                ...                         ...           ...   ...
73   서울 성북구            (주)장위가스              서울 성북구 화랑로 291   02-916-3233   성북구
74   서울 광진구           한양에너지(주)     서울 광진구 동일로 381 한양에너지(주)   02-467-8341   광진구
75   서울 노원구            태능가스(주)      서울 노원구 화랑로 405 태능가스충전소   02-972-3031   노원구
76  서울 동대문구           장안동가스충전소   서울 동대문구 천호대로 353 장안동가스충전소  02-2214-5151  동대문구
77   서울 노원구            복지노원충전소             서울 노원구 동일로 1778   02-934-9077   노원구

[78 rows x 5 columns]

In [11]:
gas_df['gas'].value_counts()

강서구     12
노원구      6
양천구      6
강남구      5
구로구      5
송파구      4
동대문구     4
서초구      4
중랑구      4
강동구      4
도봉구      3
광진구      3
은평구      3
강북구      3
영등포구     3
성동구      2
성북구      2
관악구      2
동작구      1
서대문구     1
금천구      1
Name: gas, dtype: int64

In [14]:
gas_number = pd.DataFrame(gas_df['gas'].value_counts())
gas_number['region'] = gas_number.index
gas_number = gas_number[['region','gas']]
gas_number

     region  gas
강서구     강서구   12
노원구     노원구    6
양천구     양천구    6
강남구     강남구    5
구로구     구로구    5
송파구     송파구    4
동대문구   동대문구    4
서초구     서초구    4
중랑구     중랑구    4
강동구     강동구    4
도봉구     도봉구    3
광진구     광진구    3
은평구     은평구    3
강북구     강북구    3
영등포구   영등포구    3
성동구     성동구    2
성북구     성북구    2
관악구     관악구    2
동작구     동작구    1
서대문구   서대문구    1
금천구     금천구    1

In [33]:
gas_number.to_csv('gas_raw.csv', index=False, encoding='utf-8-sig')

스케일 조정

- ~2 : 0
- 3 : 1
- 4 : 2
- 5~6 : 3
- 6~ : 4

In [18]:
gas_number.loc[gas_number['gas'] <= 2, 'gas'] = 0
gas_number.loc[(gas_number['gas'] > 2) & (gas_number['gas'] <= 3), 'gas'] = 1
gas_number.loc[(gas_number['gas'] > 3) & (gas_number['gas'] <= 4), 'gas'] = 2
gas_number.loc[(gas_number['gas'] > 4) & (gas_number['gas'] <= 6) , 'gas'] = 3
gas_number.loc[gas_number['gas'] > 6, 'gas'] = 4

In [19]:
gas_number['gas'].value_counts()

0    6
2    5
1    5
3    4
4    1
Name: gas, dtype: int64

In [20]:
gas_number

     region  gas
강서구     강서구    4
노원구     노원구    3
양천구     양천구    3
강남구     강남구    3
구로구     구로구    3
송파구     송파구    2
동대문구   동대문구    2
서초구     서초구    2
중랑구     중랑구    2
강동구     강동구    2
도봉구     도봉구    1
광진구     광진구    1
은평구     은평구    1
강북구     강북구    1
영등포구   영등포구    1
성동구     성동구    0
성북구     성북구    0
관악구     관악구    0
동작구     동작구    0
서대문구   서대문구    0
금천구     금천구    0

In [21]:
gas_number.to_csv('gas_test.csv', index=False, encoding='utf-8-sig')