In [1]:
import pandas as pd

In [12]:
hospital_df = pd.read_csv('hospital.csv', encoding='CP949')
hospital_df.head()

,id,status,tel,oldAddress,newAddress,hospitalName
0,5,영업/정상,02-2002-8000,NaN,"서울특별시 종로구 새문안로 9, 적십자병원 (평동)",서울적십자병원
1,7,영업/정상,02-2072-2655,NaN,서울특별시 종로구 대학로 101 (연건동),서울대학교치과병원
2,8,영업/정상,02-737-0181,서울특별시 종로구 무악동 32번지 2호,서울특별시 종로구 통일로 256 (무악동),세란병원
3,9,영업/정상,02-737-7582,서울특별시 종로구 숭인동 200번지 26호 진형빌딩,"서울특별시 종로구 종로 386, 6.7.8.9층 (숭인동)",서울숭인병원
4,10,영업/정상,1644-7541,서울특별시 종로구 평창동 158번지 1호 글로리아타운,"서울특별시 종로구 평창문화로 75, 글로리아타운 2,3,5층 (평창동)",로이병원

In [13]:
gu_list = []

for i in range(0, len(hospital_df)):
    if type(hospital_df['oldAddress'][i]) == float:
        addr = hospital_df['newAddress'][i].split()
        gu_list.append(addr[1])
    else:
        addr = hospital_df['oldAddress'][i].split()
        gu_list.append(addr[1])
        
print(gu_list)

['종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '용산구', '용산구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구']

In [14]:
hospital_df['hospital'] = pd.Series(gu_list)

In [15]:
hospital_df

,id,status,tel,oldAddress,newAddress,hospitalName,hospital
0,5,영업/정상,02-2002-8000,NaN,"서울특별시 종로구 새문안로 9, 적십자병원 (평동)",서울적십자병원,종로구
1,7,영업/정상,02-2072-2655,NaN,서울특별시 종로구 대학로 101 (연건동),서울대학교치과병원,종로구
2,8,영업/정상,02-737-0181,서울특별시 종로구 무악동 32번지 2호,서울특별시 종로구 통일로 256 (무악동),세란병원,종로구
3,9,영업/정상,02-737-7582,서울특별시 종로구 숭인동 200번지 26호 진형빌딩,"서울특별시 종로구 종로 386, 6.7.8.9층 (숭인동)",서울숭인병원,종로구
4,10,영업/정상,1644-7541,서울특별시 종로구 평창동 158번지 1호 글로리아타운,"서울특별시 종로구 평창문화로 75, 글로리아타운 2,3,5층 (평창동)",로이병원,종로구
...,...,...,...,...,...,...,...
441,692,영업/정상,02-480-5000,NaN,서울특별시 강동구 풍성로37길 45 (성내동),공안과병원,강동구
442,693,영업/정상,2248-7528,"서울특별시 강동구 천호2동 425번지 5호 4층 일부 (401A,401B,402,4...",서울특별시 강동구 올림픽로 664 (천호동),아이엠치과병원,강동구
443,694,영업/정상,02-441-0011,NaN,"서울특별시 강동구 올림픽로98길 8 (암사동, 동부센트럴요양병원)",동부센트럴요양병원,강동구
444,695,영업/정상,02-487-1121,서울특별시 강동구 성내동 199번지 5호,서울특별시 강동구 천호대로170길 19 (성내동),조은마디병원,강동구
445,715,영업/정상,02-441-2275,서울특별시 강동구 상일동 501번지,"서울특별시 강동구 상일로10길 36, 2층 202,203호 (상일동, 세종텔레콤지식...",연세미래엔미소치과병원,강동구

In [16]:
hospital_df['hospital'].value_counts()

강남구     70
동대문구    31
강서구     29
서초구     27
영등포구    25
송파구     25
구로구     20
노원구     20
은평구     19
강동구     18
양천구     17
강북구     15
도봉구     15
금천구     13
성북구     13
중구      12
광진구     12
중랑구     11
성동구     11
서대문구     9
마포구      9
동작구      8
관악구      8
종로구      7
용산구      2
Name: hospital, dtype: int64

In [18]:
hospital_number = pd.DataFrame(hospital_df['hospital'].value_counts())
hospital_number['region'] = hospital_number.index
hospital_number = hospital_number[['region', 'hospital']]
hospital_number

     region  hospital
강남구     강남구        70
동대문구   동대문구        31
강서구     강서구        29
서초구     서초구        27
영등포구   영등포구        25
송파구     송파구        25
구로구     구로구        20
노원구     노원구        20
은평구     은평구        19
강동구     강동구        18
양천구     양천구        17
강북구     강북구        15
도봉구     도봉구        15
금천구     금천구        13
성북구     성북구        13
중구       중구        12
광진구     광진구        12
중랑구     중랑구        11
성동구     성동구        11
서대문구   서대문구         9
마포구     마포구         9
동작구     동작구         8
관악구     관악구         8
종로구     종로구         7
용산구     용산구         2

In [19]:
hospital_number.to_csv('hospital_raw.csv', index=False, encoding='utf-8-sig')

스케일 조정

- ~ 9 : 0
- 10 ~ 13 : 1
- 14 ~ 20 : 2
- 21 ~ 31 : 3
- 32 ~ : 4

In [20]:
hospital_number.loc[hospital_number['hospital'] <= 9, 'hospital'] = 0
hospital_number.loc[(hospital_number['hospital'] > 9) & (hospital_number['hospital'] <= 13) , 'hospital'] = 1
hospital_number.loc[(hospital_number['hospital'] > 13) & (hospital_number['hospital'] <= 20) , 'hospital'] = 2
hospital_number.loc[(hospital_number['hospital'] > 20) & (hospital_number['hospital'] <= 31) , 'hospital'] = 3
hospital_number.loc[hospital_number['hospital'] > 31, 'hospital'] = 4

In [21]:
hospital_number['hospital'].value_counts()

2    7
1    6
0    6
3    5
4    1
Name: hospital, dtype: int64

In [22]:
hospital_number

     region  hospital
강남구     강남구         4
동대문구   동대문구         3
강서구     강서구         3
서초구     서초구         3
영등포구   영등포구         3
송파구     송파구         3
구로구     구로구         2
노원구     노원구         2
은평구     은평구         2
강동구     강동구         2
양천구     양천구         2
강북구     강북구         2
도봉구     도봉구         2
금천구     금천구         1
성북구     성북구         1
중구       중구         1
광진구     광진구         1
중랑구     중랑구         1
성동구     성동구         1
서대문구   서대문구         0
마포구     마포구         0
동작구     동작구         0
관악구     관악구         0
종로구     종로구         0
용산구     용산구         0

In [23]:
hospital_number.to_csv('hospital_test.csv', index=False, encoding='utf-8-sig')