In [1]:
import pandas as pd
import numpy as np

In [2]:
pop_df = pd.read_csv('seoul_pop.csv', encoding='euckr', thousands=',')
pop_df.head()

     기간  자치구    동        인구      면적   인구밀도
0  2015   합계   합계  10297138  605.25  17013
1  2015  종로구   소계    163822   23.91   6851
2  2015  종로구  사직동     10033    1.23   8157
3  2015  종로구  삼청동      3174    1.49   2130
4  2015  종로구  부암동     11217    2.27   4941

In [3]:
pop_2018 = pop_df[(pop_df['기간']==2018) & (pop_df['동']=='소계')].sort_values(by=['인구밀도'], ascending=False)
pop_2018

        기간   자치구   동      인구     면적   인구밀도
1587  2018   양천구  소계  468145  17.41  26894
1436  2018  동대문구  소계  364338  14.22  25630
1673  2018   동작구  소계  409385  16.35  25032
1451  2018   중랑구  소계  408147  18.50  22067
1627  2018   구로구  소계  438486  20.12  21793
1420  2018   광진구  소계  371063  17.06  21746
1753  2018   송파구  소계  673507  33.87  19883
1643  2018   금천구  소계  254021  13.02  19510
1402  2018   성동구  소계  316463  16.86  18771
1555  2018  서대문구  소계  323080  17.62  18331
1468  2018   성북구  소계  447687  24.57  18218
1689  2018   관악구  소계  520040  29.57  17587
1781  2018   강동구  소계  431920  24.59  17564
1503  2018   도봉구  소계  341649  20.67  16531
1654  2018  영등포구  소계  403600  24.55  16441
1538  2018   은평구  소계  487666  29.71  16415
1570  2018   마포구  소계  386359  23.85  16199
1518  2018   노원구  소계  548160  35.44  15468
1606  2018   강서구  소계  603611  41.44  14567
1730  2018   강남구  소계  547453  39.50  13859
1489  2018   강북구  소계  322915  23.60  13683
1369  2018    중구  소계  135633   9.96  13618
1385  2018   용산구  소계  245090  21.87  11209
1711  2018   서초구  소계  438163  46.98   9326
1351  2018   종로구  소계  163026  23.91   6817

In [4]:
pop_2018 = pop_2018.drop("기간", axis=1)
pop_2018 = pop_2018.drop("동", axis=1)
pop_2018 = pop_2018.drop("인구", axis=1)
pop_2018 = pop_2018.drop("면적", axis=1)

In [5]:
pop_2018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25 entries, 1587 to 1351
Data columns (total 2 columns):
자치구     25 non-null object
인구밀도    25 non-null int64
dtypes: int64(1), object(1)
memory usage: 600.0+ bytes

In [6]:
# 10000미만 인구밀도 0 
# 10000이상 15000미만 인구밀도 1
# 15000이상 20000미만 인구밀도 2
# 20000이상 25000미만 인구밀도 3
# 25000이상 인구밀도 4

pop_2018.loc[pop_2018['인구밀도'] < 10000, '인구밀도'] = 0
pop_2018.loc[((pop_2018['인구밀도'] >=10000 ) & (pop_2018['인구밀도'] < 15000)) , '인구밀도'] = 1
pop_2018.loc[((pop_2018['인구밀도'] >=15000) & (pop_2018['인구밀도'] < 20000)) , '인구밀도'] = 2
pop_2018.loc[((pop_2018['인구밀도'] >=20000) & (pop_2018['인구밀도'] < 25000)) , '인구밀도'] = 3
pop_2018.loc[pop_2018['인구밀도'] >= 25000 , '인구밀도'] = 4

In [7]:
pop_2018

       자치구  인구밀도
1587   양천구     4
1436  동대문구     4
1673   동작구     4
1451   중랑구     3
1627   구로구     3
1420   광진구     3
1753   송파구     2
1643   금천구     2
1402   성동구     2
1555  서대문구     2
1468   성북구     2
1689   관악구     2
1781   강동구     2
1503   도봉구     2
1654  영등포구     2
1538   은평구     2
1570   마포구     2
1518   노원구     2
1606   강서구     1
1730   강남구     1
1489   강북구     1
1369    중구     1
1385   용산구     1
1711   서초구     0
1351   종로구     0

In [10]:
pop_2018.to_csv("pop_density_2018.csv",index=False, encoding='utf-8-sig')