In [1]:
import pandas as pd

In [3]:
edu_df = pd.read_csv('academy_2018_raw.csv')
edu_df.index = edu_df['region']
del edu_df['region']

bar_df = pd.read_csv('danlanjujeom_raw.csv')
bar_df.index = bar_df['region']
del bar_df['region']

gas_df = pd.read_csv('gas_raw.csv')
gas_df.index = gas_df['region']
del gas_df['region']

grdp_df = pd.read_csv('grdp_df_raw.csv')
grdp_df.index = grdp_df['region']
del grdp_df['region']

hospital_df = pd.read_csv('hospital_raw.csv')
hospital_df.index = hospital_df['region']
del hospital_df['region']

park_df = pd.read_csv('park_raw.csv')
park_df.index = park_df['region']
del park_df['region']

population_df = pd.read_csv('population_density_2018_raw.csv')
population_df.index = population_df['region']
del population_df['region']

store_df = pd.read_csv('store_raw.csv')
store_df.index = store_df['region']
del store_df['region']

theater_df = pd.read_csv('theater_raw.csv')
theater_df.index = theater_df['region']
del theater_df['region']

saloon_df = pd.read_csv('uheungjujeom_raw.csv')
saloon_df.index = saloon_df['region']
del saloon_df['region']

waste_df = pd.read_csv('waste_raw.csv')
waste_df.index = waste_df['region']
del waste_df['region']

y_data = pd.read_csv('increase_rate.csv')
y_data.index = y_data['region']
del y_data['region']

In [4]:
raw_real_estate_df = pd.concat([edu_df, bar_df, gas_df, grdp_df, hospital_df, park_df, population_df, store_df,
        theater_df, saloon_df, waste_df, y_data], axis=1, ignore_index=False)
raw_real_estate_df

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,education,bar,gas,GRDP,population,hospital,park,density,store,theater,saloon,waste,meanRate
강남구,"2,263",254,5.0,"59,981,514","534,889",70,7,"13,859",49,15.0,211,1,56.50
강동구,638,92,4.0,"7,424,711","434,929",18,7,"17,564",26,3.0,130,10,43.68
강북구,218,121,3.0,"2,830,150","317,889",15,3,"13,683",24,2.0,70,7,22.85
강서구,707,168,12.0,"10,739,720","573,224",29,9,"14,567",27,3.0,126,28,40.44
관악구,450,92,2.0,"5,358,231","519,316",8,2,"17,587",24,NaN,205,11,35.64
광진구,430,79,3.0,"5,970,256","366,874",12,2,"21,746",27,4.0,17,10,48.73
구로구,427,93,5.0,"11,964,909","442,766",20,4,"21,793",38,5.0,34,28,54.28
금천구,222,71,1.0,"15,004,950","248,820",13,4,"19,510",25,NaN,48,7,25.65
노원구,747,47,6.0,"5,292,768","560,350",20,2,"15,468",19,3.0,21,34,31.71
도봉구,335,50,3.0,"2,816,851","339,015",15,6,"16,531",16,1.0,23,10,35.28
동대문구,363,87,4.0,"7,180,082","361,834",31,4,"25,630",33,1.0,73,17,64.50
동작구,458,44,1.0,"5,184,807","408,043",8,7,"25,032",16,1.0,49,9,39.31
마포구,644,81,NaN,"16,355,733","376,613",9,5,"16,199",29,4.0,60,16,53.03
서대문구,345,61,1.0,"7,452,206","318,355",9,4,"18,331",12,4.0,30,37,43.51
서초구,"1,130",109,4.0,"29,493,607","418,215",27,6,"9,326",31,2.0,62,18,52.45
성동구,314,41,2.0,"10,503,045","294,822",11,5,"18,771",21,2.0,23,66,64.26
성북구,464,64,2.0,"5,217,211","452,601",13,3,"18,218",41,3.0,8,10,35.46
송파구,"1,051",153,4.0,"22,002,209","627,130",25,7,"19,883",42,3.0,94,12,54.21
양천구,"1,062",69,6.0,"6,022,303","462,973",17,4,"26,894",24,2.0,4,12,46.17
영등포구,467,232,3.0,"27,701,698","403,389",25,5,"16,441",41,2.0,154,21,56.05
용산구,158,102,NaN,"10,308,398","225,202",2,2,"11,209",21,1.0,28,2,57.19
은평구,521,131,3.0,"3,929,828","474,795",19,7,"16,415",30,3.0,84,9,27.93
종로구,274,126,NaN,"28,036,775","159,940",7,12,"6,817",17,9.0,208,1,43.21
중구,119,87,NaN,"48,654,807","127,482",12,3,"13,618",59,14.0,227,2,34.80
중랑구,273,102,4.0,"4,013,154","402,615",11,6,"22,067",15,2.0,22,16,34.11

In [7]:
raw_real_estate_df = raw_real_estate_df.fillna(0)
raw_real_estate_df

,education,bar,gas,GRDP,population,hospital,park,density,store,theater,saloon,waste,meanRate
강남구,"2,263",254,5.0,"59,981,514","534,889",70,7,"13,859",49,15.0,211,1,56.50
강동구,638,92,4.0,"7,424,711","434,929",18,7,"17,564",26,3.0,130,10,43.68
강북구,218,121,3.0,"2,830,150","317,889",15,3,"13,683",24,2.0,70,7,22.85
강서구,707,168,12.0,"10,739,720","573,224",29,9,"14,567",27,3.0,126,28,40.44
관악구,450,92,2.0,"5,358,231","519,316",8,2,"17,587",24,0.0,205,11,35.64
광진구,430,79,3.0,"5,970,256","366,874",12,2,"21,746",27,4.0,17,10,48.73
구로구,427,93,5.0,"11,964,909","442,766",20,4,"21,793",38,5.0,34,28,54.28
금천구,222,71,1.0,"15,004,950","248,820",13,4,"19,510",25,0.0,48,7,25.65
노원구,747,47,6.0,"5,292,768","560,350",20,2,"15,468",19,3.0,21,34,31.71
도봉구,335,50,3.0,"2,816,851","339,015",15,6,"16,531",16,1.0,23,10,35.28
동대문구,363,87,4.0,"7,180,082","361,834",31,4,"25,630",33,1.0,73,17,64.50
동작구,458,44,1.0,"5,184,807","408,043",8,7,"25,032",16,1.0,49,9,39.31
마포구,644,81,0.0,"16,355,733","376,613",9,5,"16,199",29,4.0,60,16,53.03
서대문구,345,61,1.0,"7,452,206","318,355",9,4,"18,331",12,4.0,30,37,43.51
서초구,"1,130",109,4.0,"29,493,607","418,215",27,6,"9,326",31,2.0,62,18,52.45
성동구,314,41,2.0,"10,503,045","294,822",11,5,"18,771",21,2.0,23,66,64.26
성북구,464,64,2.0,"5,217,211","452,601",13,3,"18,218",41,3.0,8,10,35.46
송파구,"1,051",153,4.0,"22,002,209","627,130",25,7,"19,883",42,3.0,94,12,54.21
양천구,"1,062",69,6.0,"6,022,303","462,973",17,4,"26,894",24,2.0,4,12,46.17
영등포구,467,232,3.0,"27,701,698","403,389",25,5,"16,441",41,2.0,154,21,56.05
용산구,158,102,0.0,"10,308,398","225,202",2,2,"11,209",21,1.0,28,2,57.19
은평구,521,131,3.0,"3,929,828","474,795",19,7,"16,415",30,3.0,84,9,27.93
종로구,274,126,0.0,"28,036,775","159,940",7,12,"6,817",17,9.0,208,1,43.21
중구,119,87,0.0,"48,654,807","127,482",12,3,"13,618",59,14.0,227,2,34.80
중랑구,273,102,4.0,"4,013,154","402,615",11,6,"22,067",15,2.0,22,16,34.11