In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import numpy as np
from matplotlib import rcParams
plt.rc('font', family='Malgun Gothic')
plt.rc('font', size='10')

In [2]:
rebuild_df = pd.read_csv('rebuild.csv', encoding='euckr')
rebuild_df.head()

,사업번호,자치구,법정동,사업구분,운영구분,추진위원회/조합명,대표지번,진행단계,상태,정비구역명칭,...,건폐율,용적률,높이(m),지상층수,지하층수,건설세대총수,60미만건설세대수,60이상85이하건설세대수,85초과건설세대수,건축계획비고
0,11560-900000508,영등포구,NaN,도시환경정비,공공지원자,23. 영등포1-7 재정비촉진구역,영등포동5가 49-1,정비구역지정,일시중단,영등포1-7 재정비촉진구역,...,65.00,570.00,60.0,18.0,4.0,NaN,75.0,40.0,NaN,NaN
1,11290-100001003,성북구,NaN,재개발,추진위원회,정릉제3구역주택재개발정비사업 조합설립추진위원회,정릉동 894,조합설립추진위원회승인,일시중단,정릉3구역주택재개발정비사업조합추진위원회,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11305-100005002,강북구,NaN,재개발,추진위원회,미아제16구역 주택재개발사업 조합설립추진위원회,미아동 6,조합설립추진위원회승인,일시중단,미아제16구역주택재개발정비사업조합설립추진위원회,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11260-900000170,중랑구,NaN,재개발,공공지원자,중화2재정비촉진구역 주택재개발정비사업,중화동 329-38,정비구역지정,일시중단,중화2재정비촉진구역 주택재개발정비사업,...,30.00,295.30,125.0,34.0,2.0,2317.0,985.0,680.0,652.0,부분임대326
4,11560-900000180,영등포구,NaN,재건축,공공지원자,신길13재정비촉진구역,신길동 340-1,정비구역지정,일시중단,신길13재정비촉진구역,...,20.84,248.61,NaN,22.0,NaN,217.0,26.0,87.0,104.0,NaN

In [3]:
rebuild_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 627 entries, 0 to 626
Data columns (total 33 columns):
사업번호             627 non-null object
자치구              627 non-null object
법정동              0 non-null float64
사업구분             627 non-null object
운영구분             627 non-null object
추진위원회/조합명        627 non-null object
대표지번             627 non-null object
진행단계             627 non-null object
상태               627 non-null object
정비구역명칭           589 non-null object
정비구역위치           589 non-null object
정비구역면적(㎡)        582 non-null float64
건축연면적(㎡)         467 non-null float64
용도지역             545 non-null object
용도지구             353 non-null object
택지면적(㎡)          502 non-null float64
도로면적(㎡)          479 non-null float64
공원면적(㎡)          407 non-null float64
녹지면적(㎡)          185 non-null float64
공공공지면적(㎡)        178 non-null float64
학교면적(㎡)          124 non-null float64
기타면적(㎡)          201 non-null float64
주용도              527 non-null object
건폐율              537 non-null float64
용적률              541 non-null float64
높이(m)            400 non-null float64
지상층수             492 non-null float64
지하층수             466 non-null float64
건설세대총수           372 non-null float64
60미만건설세대수        473 non-null float64
60이상85이하건설세대수    505 non-null float64
85초과건설세대수        413 non-null float64
건축계획비고           72 non-null object
dtypes: float64(19), object(14)
memory usage: 161.8+ KB

In [4]:
rebuild_count_df = pd.DataFrame(rebuild_df['자치구'].value_counts())
rebuild_count_df.rename(columns=lambda x: x.replace('자치구', '재개발'), inplace=True)
rebuild_count_df

      재개발
영등포구   68
서초구    57
성북구    48
강남구    40
동대문구   38
은평구    34
서대문구   31
용산구    31
성동구    27
강동구    27
송파구    26
동작구    22
강서구    20
마포구    20
양천구    18
강북구    18
관악구    16
중랑구    15
노원구    13
광진구    12
구로구    12
종로구    12
금천구    11
중구      6
도봉구     5

In [6]:
rebuild_count_df['자치구'] = rebuild_count_df.index

In [8]:
rebuild_count_df = rebuild_count_df[['자치구','재개발']]

In [9]:
rebuild_count_df

       자치구  재개발
영등포구  영등포구   68
서초구    서초구   57
성북구    성북구   48
강남구    강남구   40
동대문구  동대문구   38
은평구    은평구   34
서대문구  서대문구   31
용산구    용산구   31
성동구    성동구   27
강동구    강동구   27
송파구    송파구   26
동작구    동작구   22
강서구    강서구   20
마포구    마포구   20
양천구    양천구   18
강북구    강북구   18
관악구    관악구   16
중랑구    중랑구   15
노원구    노원구   13
광진구    광진구   12
구로구    구로구   12
종로구    종로구   12
금천구    금천구   11
중구      중구    6
도봉구    도봉구    5

In [10]:
rebuild_count_df.to_csv('rebuild_count_raw.csv', index=False, encoding='utf-8-sig')

In [11]:
rebuild_count_df.loc[rebuild_count_df['재개발'] < 10, '재개발'] = 0
rebuild_count_df.loc[(rebuild_count_df['재개발'] >= 10) & (rebuild_count_df['재개발'] < 15) , '재개발'] = 1
rebuild_count_df.loc[(rebuild_count_df['재개발'] >= 15) & (rebuild_count_df['재개발'] < 25) , '재개발'] = 2
rebuild_count_df.loc[(rebuild_count_df['재개발'] >= 25) & (rebuild_count_df['재개발'] < 40) , '재개발'] = 3
rebuild_count_df.loc[rebuild_count_df['재개발'] >= 40, '재개발'] = 4

In [12]:
rebuild_count_df

       자치구  재개발
영등포구  영등포구    4
서초구    서초구    4
성북구    성북구    4
강남구    강남구    4
동대문구  동대문구    3
은평구    은평구    3
서대문구  서대문구    3
용산구    용산구    3
성동구    성동구    3
강동구    강동구    3
송파구    송파구    3
동작구    동작구    2
강서구    강서구    2
마포구    마포구    2
양천구    양천구    2
강북구    강북구    2
관악구    관악구    2
중랑구    중랑구    2
노원구    노원구    1
광진구    광진구    1
구로구    구로구    1
종로구    종로구    1
금천구    금천구    1
중구      중구    0
도봉구    도봉구    0

In [13]:
rebuild_count_df.to_csv('rebuild_count.csv', index=False, encoding='utf-8-sig')