# 자치구별 지역총생산을 네가지 카테고리로 분류하기

In [4]:
import pandas as pd
import numpy as np


grdp_df = pd.read_csv('grdp_df.csv', thousands=',')
grdp_df

   district      GRDP  population
0       종로구  28036775      159940
1        중구  48654807      127482
2       용산구  10308398      225202
3       성동구  10503045      294822
4       광진구   5970256      366874
5      동대문구   7180082      361834
6       중랑구   4013154      402615
7       성북구   5217211      452601
8       강북구   2830150      317889
9       도봉구   2816851      339015
10      노원구   5292768      560350
11      은평구   3929828      474795
12     서대문구   7452206      318355
13      마포구  16355733      376613
14      양천구   6022303      462973
15      강서구  10739720      573224
16      구로구  11964909      442766
17      금천구  15004950      248820
18     영등포구  27701698      403389
19      동작구   5184807      408043
20      관악구   5358231      519316
21      서초구  29493607      418215
22      강남구  59981514      534889
23      송파구  22002209      627130
24      강동구   7424711      434929

### GRDP 구분하기

In [5]:
# 5000000이하  GRDP 0 
# 5000000이상 10000000이하 GRDP 1 
# 10000000이상 20000000이하 GRDP 2 
# 20000000이상 30000000이하 GRDP 3 
# 30000000이상 GRDP 4

# 평균값 14377596
# 중앙값 7452206
# 최솟값 2816851
# 최댓값 59981514

grdp_df.loc[grdp_df['GRDP'] < 5000000.0, 'GRDP'] = 0
grdp_df.loc[((grdp_df['GRDP'] >=5000000.0 ) & (grdp_df['GRDP'] < 10000000.0)) , 'GRDP'] = 1
grdp_df.loc[((grdp_df['GRDP'] >=10000000.0) & (grdp_df['GRDP'] < 20000000.0)) , 'GRDP'] = 2
grdp_df.loc[((grdp_df['GRDP'] >=20000000.0) & (grdp_df['GRDP'] < 30000000.0)) , 'GRDP'] = 3
grdp_df.loc[grdp_df['GRDP'] >= 30000000.0 , 'GRDP'] = 4

grdp_df

   district  GRDP  population
0       종로구     3      159940
1        중구     4      127482
2       용산구     2      225202
3       성동구     2      294822
4       광진구     1      366874
5      동대문구     1      361834
6       중랑구     0      402615
7       성북구     1      452601
8       강북구     0      317889
9       도봉구     0      339015
10      노원구     1      560350
11      은평구     0      474795
12     서대문구     1      318355
13      마포구     2      376613
14      양천구     1      462973
15      강서구     2      573224
16      구로구     2      442766
17      금천구     2      248820
18     영등포구     3      403389
19      동작구     1      408043
20      관악구     1      519316
21      서초구     3      418215
22      강남구     4      534889
23      송파구     3      627130
24      강동구     1      434929

In [6]:
# DataFrame으로 저장하기
grdp_df.to_csv('grdp_cate.csv', encoding='utf-8-sig', index=False)