In [1]:
import pandas as pd

In [2]:
store_df = pd.read_csv('store.csv', encoding = 'CP949')
store_df.head()

,id,status,oldAddress,newAddress,storeName
0,1,영업/정상,서울특별시 종로구 낙원동 288번지 낙원상가,"서울특별시 종로구 삼일대로 428, 낙원상가 506호 (낙원동)",낙원상가
1,2,영업/정상,서울특별시 종로구 낙원동 288번지 낙원상가,"서울특별시 종로구 삼일대로 428, 낙원상가 (낙원동)",낙원상가
2,3,영업/정상,서울특별시 종로구 예지동 6번지 1호,NaN,광장주식회사
3,4,영업/정상,서울특별시 종로구 종로1가 1번지,서울특별시 종로구 종로 1 (종로1가),종로1번지아케이트
4,5,영업/정상,서울특별시 종로구 서린동 33호,NaN,영풍문고

In [19]:
gu_list = []

for i in range(0, len(store_df)):
    if type(store_df['oldAddress'][i]) == float:
        addr = store_df['newAddress'][i].split()
        gu_list.append(addr[1])
    else:
        addr = store_df['oldAddress'][i].split()
        gu_list.append(addr[1])

print(gu_list)

['종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '종로구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '중구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '용산구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '성동구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '광진구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '동대문구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '중랑구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '성북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '강북구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '도봉구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '노원구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '은평구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '서대문구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '마포구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '양천구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '강서구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '구로구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '금천구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '영등포구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '동작구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '관악구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '서초구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '강남구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '송파구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구', '강동구']

In [10]:
store_df['store'] = pd.Series(gu_list)

In [11]:
store_df

,id,status,oldAddress,newAddress,storeName,store
0,1,영업/정상,서울특별시 종로구 낙원동 288번지 낙원상가,"서울특별시 종로구 삼일대로 428, 낙원상가 506호 (낙원동)",낙원상가,종로구
1,2,영업/정상,서울특별시 종로구 낙원동 288번지 낙원상가,"서울특별시 종로구 삼일대로 428, 낙원상가 (낙원동)",낙원상가,종로구
2,3,영업/정상,서울특별시 종로구 예지동 6번지 1호,NaN,광장주식회사,종로구
3,4,영업/정상,서울특별시 종로구 종로1가 1번지,서울특별시 종로구 종로 1 (종로1가),종로1번지아케이트,종로구
4,5,영업/정상,서울특별시 종로구 서린동 33호,NaN,영풍문고,종로구
...,...,...,...,...,...,...
702,886,영업/정상,서울특별시 강동구 성내1동 451번지,서울특별시 강동구 올림픽로 528 (성내동),(주)농협유통 하나로마트 성내점,강동구
703,914,영업/정상,서울특별시 강동구 성내동 595번지 코오롱 2차아파트,"서울특별시 강동구 올림픽로 572, 상가동 1층 101,102호 (성내동, 코오롱 ...",이마트에브리데이 성내점,강동구
704,915,영업/정상,서울특별시 강동구 고덕동 212번지 고덕그라시움아파트,"서울특별시 강동구 고덕로 333, 상가 1동 지하1층 108-119,128호 (고덕...",지에스 더프레시(GS THE FRESH) 고덕그라시움점,강동구
705,916,영업/정상,서울특별시 강동구 명일동 46번지 4호,NaN,신세계 이마트 명일점,강동구
706,917,영업/정상,서울특별시 강동구 암사3동 451번지 16호,NaN,양지종합시장,강동구

In [12]:
store_df['store'].value_counts()

중구      59
강남구     49
송파구     42
성북구     41
영등포구    41
구로구     38
동대문구    33
서초구     31
은평구     30
마포구     29
광진구     27
강서구     27
강동구     26
금천구     25
관악구     24
양천구     24
강북구     24
성동구     21
용산구     21
노원구     19
종로구     17
동작구     16
도봉구     16
중랑구     15
서대문구    12
Name: store, dtype: int64

In [16]:
store_number = pd.DataFrame(store_df['store'].value_counts())
store_number['region'] = store_number.index
store_number = store_number[['region','store']]
store_number

     region  store
중구       중구     59
강남구     강남구     49
송파구     송파구     42
성북구     성북구     41
영등포구   영등포구     41
구로구     구로구     38
동대문구   동대문구     33
서초구     서초구     31
은평구     은평구     30
마포구     마포구     29
광진구     광진구     27
강서구     강서구     27
강동구     강동구     26
금천구     금천구     25
관악구     관악구     24
양천구     양천구     24
강북구     강북구     24
성동구     성동구     21
용산구     용산구     21
노원구     노원구     19
종로구     종로구     17
동작구     동작구     16
도봉구     도봉구     16
중랑구     중랑구     15
서대문구   서대문구     12

In [17]:
store_number.to_csv('store_raw.csv', index=False, encoding='utf-8-sig')

스케일 조정

- ~ 20 : 0
- 21 ~ 25 : 1
- 26 ~ 30 : 2
- 31 ~ 45 : 3
- 46 ~ : 4

In [20]:
store_number.loc[store_number['store'] <= 20, 'store'] = 0
store_number.loc[(store_number['store'] > 20) & (store_number['store'] <= 25) , 'store'] = 1
store_number.loc[(store_number['store'] > 25) & (store_number['store'] <= 30) , 'store'] = 2
store_number.loc[(store_number['store'] > 30) & (store_number['store'] <= 45) , 'store'] = 3
store_number.loc[store_number['store'] > 45, 'store'] = 4

In [21]:
store_number['store'].value_counts()

3    6
1    6
0    6
2    5
4    2
Name: store, dtype: int64

In [22]:
store_number

     region  store
중구       중구      4
강남구     강남구      4
송파구     송파구      3
성북구     성북구      3
영등포구   영등포구      3
구로구     구로구      3
동대문구   동대문구      3
서초구     서초구      3
은평구     은평구      2
마포구     마포구      2
광진구     광진구      2
강서구     강서구      2
강동구     강동구      2
금천구     금천구      1
관악구     관악구      1
양천구     양천구      1
강북구     강북구      1
성동구     성동구      1
용산구     용산구      1
노원구     노원구      0
종로구     종로구      0
동작구     동작구      0
도봉구     도봉구      0
중랑구     중랑구      0
서대문구   서대문구      0

In [23]:
store_number.to_csv('store_test.csv', index = False, encoding='utf-8-sig')